/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Matches
         * @description Offers ranked by fit. ``mode=basic`` uses rules only; ``mode=ai`` also asks the configured model.
         */
        get: operations["get_matches_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Offer
         * @description Offer from the local database (``source:external_id``), with its description fetched on demand.
         */
        get: operations["get_offer_offers__offer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offer_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Offer Status
         * @description Mark an offer as saved or hidden (hidden offers are left out of /matches); null clears the mark.
         */
        put: operations["set_offer_status_offers__offer_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{offer_id}/assess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assess Offer
         * @description AI-assess one offer, e.g. one outside the top N rated in /matches?mode=ai.
         */
        post: operations["assess_offer_offers__offer_id__assess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Current profile; rebuilt automatically when the CV file changed.
         */
        get: operations["get_profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild Profile */
        post: operations["rebuild_profile_profile_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Cv
         * @description Upload a new CV (PDF). It becomes the newest file in the CV folder and the profile is rebuilt.
         */
        post: operations["upload_cv_profile_cv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overrides */
        get: operations["get_overrides_profile_overrides_get"];
        /**
         * Put Overrides
         * @description Replace manual profile corrections (kept across CV changes) and return the resulting profile.
         */
        put: operations["put_overrides_profile_overrides_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_sources__source__categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Sync
         * @description Start downloading offers in the background; poll GET /sync/status for progress.
         */
        post: operations["start_sync_sync_post"];
        /**
         * Cancel Sync
         * @description Stop the running sync; offers downloaded so far are kept.
         */
        delete: operations["cancel_sync_sync_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/syncs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync History */
        get: operations["sync_history_syncs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Searches
         * @description The default search and every [searches.<name>] preset from config.toml, with offer counts.
         */
        get: operations["searches_searches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preferences
         * @description Effective search preferences: config.toml [search], optionally with a named preset applied.
         */
        get: operations["preferences_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIAssessment
         * @description Structured answer every AI scorer must return.
         */
        AIAssessment: {
            /**
             * Score
             * @description Overall fit of the candidate for the offer
             */
            score: number;
            /**
             * Summary
             * @description Two or three sentences in Polish explaining the score
             */
            summary: string;
            /**
             * Pros
             * @description Reasons the candidate fits, in Polish
             */
            pros: string[];
            /**
             * Cons
             * @description Gaps or risks, in Polish
             */
            cons: string[];
            /**
             * Missing Skills
             * @description Skills the offer needs that the candidate lacks
             */
            missing_skills: string[];
        };
        /** AIResult */
        AIResult: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            assessment: components["schemas"]["AIAssessment"];
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** AISettings */
        AISettings: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Top N */
            top_n: number;
            /** Weight */
            weight: number;
        };
        /** AIUsage */
        AIUsage: {
            /** Provider */
            provider: string | null;
            /** Model */
            model: string | null;
            /** Calls */
            calls: number;
            /** Cached */
            cached: number;
            /** Failed */
            failed: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Errors */
            errors: string[];
        };
        /** Body_upload_cv_profile_cv_post */
        Body_upload_cv_profile_cv_post: {
            /** File */
            file: string;
        };
        /** CandidateProfile */
        CandidateProfile: {
            /**
             * Parser Version
             * @description Version of the CV parser that built this profile
             * @default 0
             */
            parser_version: number;
            /** Source File */
            source_file: string | null;
            /**
             * Source Hash
             * @description SHA-256 of the CV file the profile was built from
             */
            source_hash: string | null;
            /** Built At */
            built_at: string | null;
            /** Headline */
            headline: string | null;
            /** Location */
            location: string | null;
            /**
             * Years Of Experience
             * @default 0
             */
            years_of_experience: number;
            /** @default mid */
            seniority: components["schemas"]["Seniority"];
            /** Skills */
            skills: components["schemas"]["CandidateSkill"][];
            /**
             * Skill Years
             * @description Canonical skill -> years used in positions listed in the CV
             */
            skill_years: {
                [key: string]: number;
            };
            /**
             * Languages
             * @description ISO code -> CEFR level
             */
            languages: {
                [key: string]: string;
            };
            /**
             * Cv Text
             * @description CV text with contact data removed; sent to AI scorers
             * @default
             */
            cv_text: string;
        };
        /** CandidateSkill */
        CandidateSkill: {
            /**
             * Name
             * @description Canonical skill name, see profile.skill_extractor
             */
            name: string;
            /**
             * Weight
             * @description 1.0 = core skill, lower = secondary
             * @default 1
             */
            weight: number;
        };
        /** CategoryInfo */
        CategoryInfo: {
            /** Key */
            key: string;
            /** Count */
            count: number | null;
        };
        /** ExperienceSettings */
        ExperienceSettings: {
            /** Transfer Ratio */
            transfer_ratio: number;
            /** Declared Ratio */
            declared_ratio: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOffer */
        JobOffer: {
            /** Source */
            source: string;
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Category */
            category: string | null;
            seniority: components["schemas"]["Seniority"] | null;
            workplace_type: components["schemas"]["WorkplaceType"] | null;
            /** Working Time */
            working_time: string | null;
            /** Locations */
            locations: components["schemas"]["Location"][];
            /** Required Skills */
            required_skills: components["schemas"]["Skill"][];
            /** Nice To Have Skills */
            nice_to_have_skills: components["schemas"]["Skill"][];
            /** Languages */
            languages: components["schemas"]["LanguageRequirement"][];
            /** Salaries */
            salaries: components["schemas"]["Salary"][];
            /** Published At */
            published_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Apply Url */
            apply_url: string | null;
            /**
             * Description
             * @description Plain-text description, filled by fetch_details
             */
            description: string | null;
            /**
             * Extra
             * @description Source-specific identifiers, e.g. slug
             */
            extra: {
                [key: string]: string;
            };
            /**
             * Id
             * @description Globally unique id: ``source:external_id``.
             */
            readonly id: string;
        };
        /** LanguageRequirement */
        LanguageRequirement: {
            /**
             * Code
             * @description ISO 639-1 language code, e.g. 'en'
             */
            code: string;
            /**
             * Level
             * @description CEFR level, e.g. 'B2'
             */
            level: string | null;
        };
        /** Location */
        Location: {
            /** City */
            city: string;
            /** Street */
            street: string | null;
        };
        /** MatchResponse */
        MatchResponse: {
            mode: components["schemas"]["MatchingMode"];
            /** Considered */
            considered: number;
            /** Filtered Out */
            filtered_out: number;
            /** Passed */
            passed: number;
            /** Profile Hash */
            profile_hash: string;
            /** Profile Rebuilt */
            profile_rebuilt: boolean;
            /** Warning */
            warning: string | null;
            preferences: components["schemas"]["SearchPreferences"];
            ai: components["schemas"]["AIUsage"] | null;
            /** Results */
            results: components["schemas"]["MatchResult"][];
        };
        /** MatchResult */
        MatchResult: {
            offer: components["schemas"]["JobOffer"];
            rule: components["schemas"]["RuleScore"];
            ai: components["schemas"]["AIResult"] | null;
            /** Final Score */
            final_score: number;
            /**
             * Status
             * @description The user's mark on the offer
             */
            status: ("saved" | "hidden") | null;
        };
        /**
         * MatchingMode
         * @enum {string}
         */
        MatchingMode: "basic" | "ai";
        /** OfferStatusUpdate */
        OfferStatusUpdate: {
            /** Status */
            status: ("saved" | "hidden") | null;
        };
        /**
         * ProfileOverrides
         * @description Manual corrections applied on top of the profile parsed from the CV.
         */
        "ProfileOverrides-Input": {
            /**
             * Add Skills
             * @description Added as core skills
             */
            add_skills?: string[];
            /** Remove Skills */
            remove_skills?: string[];
            /**
             * Skill Weights
             * @description Skill -> weight 0..1
             */
            skill_weights?: {
                [key: string]: number;
            };
            /**
             * Skill Years
             * @description Skill -> years of commercial use, e.g. {'python': 2}
             */
            skill_years?: {
                [key: string]: number;
            };
            /** Years Of Experience */
            years_of_experience?: number | null;
            seniority?: components["schemas"]["Seniority"] | null;
            /**
             * Languages
             * @description ISO code -> CEFR level
             */
            languages?: {
                [key: string]: string;
            };
            /**
             * Extra Notes
             * @description Extra context for AI scoring, e.g. what you want
             */
            extra_notes?: string | null;
        };
        /**
         * ProfileOverrides
         * @description Manual corrections applied on top of the profile parsed from the CV.
         */
        "ProfileOverrides-Output": {
            /**
             * Add Skills
             * @description Added as core skills
             */
            add_skills: string[];
            /** Remove Skills */
            remove_skills: string[];
            /**
             * Skill Weights
             * @description Skill -> weight 0..1
             */
            skill_weights: {
                [key: string]: number;
            };
            /**
             * Skill Years
             * @description Skill -> years of commercial use, e.g. {'python': 2}
             */
            skill_years: {
                [key: string]: number;
            };
            /** Years Of Experience */
            years_of_experience: number | null;
            seniority: components["schemas"]["Seniority"] | null;
            /**
             * Languages
             * @description ISO code -> CEFR level
             */
            languages: {
                [key: string]: string;
            };
            /**
             * Extra Notes
             * @description Extra context for AI scoring, e.g. what you want
             */
            extra_notes: string | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            profile: components["schemas"]["CandidateProfile"];
            /** Profile Hash */
            profile_hash: string;
            /** Rebuilt */
            rebuilt: boolean;
            /** Warning */
            warning: string | null;
        };
        /** RuleScore */
        RuleScore: {
            /** Score */
            score: number;
            /**
             * Breakdown
             * @description Component -> 0..1
             */
            breakdown: {
                [key: string]: number;
            };
            /** Matched Skills */
            matched_skills: string[];
            /** Missing Skills */
            missing_skills: string[];
            /** Notes */
            notes: string[];
            /**
             * Effective Years
             * @description Candidate's experience in this offer's main technologies
             */
            effective_years: number | null;
            effective_level: components["schemas"]["Seniority"] | null;
            /**
             * Main Skills
             * @description Offer skills used for effective_years
             */
            main_skills: string[];
        };
        /** RuleWeights */
        RuleWeights: {
            /**
             * Skills
             * @default 0.45
             */
            skills: number;
            /**
             * Title
             * @default 0.1
             */
            title: number;
            /**
             * Seniority
             * @default 0.15
             */
            seniority: number;
            /**
             * Location
             * @default 0.1
             */
            location: number;
            /**
             * Salary
             * @default 0.1
             */
            salary: number;
            /**
             * Languages
             * @default 0.05
             */
            languages: number;
            /**
             * Freshness
             * @default 0.05
             */
            freshness: number;
        };
        /**
         * Salary
         * @description Salary range normalized to PLN per month.
         */
        Salary: {
            /**
             * Contract
             * @description b2b, permanent, mandate_contract, internship or any
             */
            contract: string;
            /** Min Pln Month */
            min_pln_month: number | null;
            /** Max Pln Month */
            max_pln_month: number | null;
            /** Gross */
            gross: boolean | null;
            /** Original Currency */
            original_currency: string | null;
            /** Original Unit */
            original_unit: string | null;
            /** Original Min */
            original_min: number | null;
            /** Original Max */
            original_max: number | null;
        };
        /**
         * SearchPreferences
         * @description What the user is looking for. Every field can be overridden per request (CLI flags / API params).
         */
        SearchPreferences: {
            /** Sources */
            sources: string[];
            /** Categories */
            categories: string[];
            /**
             * Experience Levels
             * @description 'auto' = your level in the offer's technologies plus one level up; or an explicit list
             * @default auto
             */
            experience_levels: components["schemas"]["Seniority"][] | "auto";
            /** Workplace */
            workplace: components["schemas"]["WorkplaceType"][];
            /** Preferred Cities */
            preferred_cities: string[];
            /**
             * Onsite Only In Preferred Cities
             * @description Drop hybrid/office offers that are not located in one of preferred_cities
             * @default true
             */
            onsite_only_in_preferred_cities: boolean;
            /** Min Salary Pln Month */
            min_salary_pln_month: number | null;
            /**
             * Exclude Keywords
             * @description Whole words matched in title and skills
             */
            exclude_keywords: string[];
            /**
             * Title Keywords
             * @description Words that make a job title attractive (core skills from the CV count automatically)
             */
            title_keywords: string[];
            /**
             * Avoid Title Keywords
             * @description Words that make a job title unattractive (soft penalty, not a filter)
             */
            avoid_title_keywords: string[];
            /**
             * Target Skills
             * @description Skills you are moving towards (e.g. C++): partial credit in matching, told to the AI scorer
             */
            target_skills: string[];
            /**
             * Max Offer Age Days
             * @default 45
             */
            max_offer_age_days: number | null;
        };
        /** SearchSummaryItem */
        SearchSummaryItem: {
            /**
             * Name
             * @description Preset name; null for the default [search] section
             */
            name: string | null;
            preferences: components["schemas"]["SearchPreferences"];
            /**
             * Considered
             * @description Offers in the database for this search
             */
            considered: number;
            /**
             * Passed
             * @description Offers that pass the hard filters (after merging duplicates)
             */
            passed: number;
            /**
             * Needs Sync
             * @description No offers of this search's categories have been downloaded yet
             */
            needs_sync: boolean;
        };
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "intern" | "junior" | "mid" | "senior" | "manager" | "c_level";
        /**
         * Settings
         * @description Read-only configuration the UI uses for labels and explanations.
         */
        Settings: {
            default_mode: components["schemas"]["MatchingMode"];
            weights: components["schemas"]["RuleWeights"];
            experience: components["schemas"]["ExperienceSettings"];
            ai: components["schemas"]["AISettings"];
        };
        /** Skill */
        Skill: {
            /** Name */
            name: string;
            /**
             * Level
             * @description Required proficiency, 1 (basic) to 5 (expert)
             */
            level: number | null;
        };
        /** SourceStatus */
        SourceStatus: {
            /** Name */
            name: string;
            /** Offers In Db */
            offers_in_db: number;
            /** Last Sync Started */
            last_sync_started: string | null;
            /** Last Sync Finished */
            last_sync_finished: string | null;
            /** Last Sync Fetched */
            last_sync_fetched: number | null;
            /** Last Sync New */
            last_sync_new: number | null;
            /** Last Sync Error */
            last_sync_error: string | null;
        };
        /** SyncHistoryItem */
        SyncHistoryItem: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Categories
             * @description Empty: all categories; null: not recorded (older runs)
             */
            categories: string[] | null;
            /** Fetched */
            fetched: number;
            /** New */
            new: number;
            /** Error */
            error: string | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Sources
             * @description Default: search.sources from config
             */
            sources?: string[] | null;
            /**
             * Categories
             * @description Default: search.categories from config
             */
            categories?: string[] | null;
            /**
             * Search
             * @description Take sources/categories from a named search preset
             */
            search?: string | null;
            /** Limit */
            limit?: number | null;
        };
        /** SyncResultItem */
        SyncResultItem: {
            /** Source */
            source: string;
            /** Fetched */
            fetched: number;
            /** New */
            new: number;
            /** Error */
            error: string | null;
        };
        /** SyncStatus */
        SyncStatus: {
            /** Running */
            running: boolean;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Source */
            source: string | null;
            /** Category */
            category: string | null;
            /** Category Index */
            category_index: number;
            /** Category Count */
            category_count: number;
            /** Fetched */
            fetched: number;
            /** Total */
            total: number | null;
            /** Cancelled */
            cancelled: boolean;
            /** Error */
            error: string | null;
            /** Results */
            results: components["schemas"]["SyncResultItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkplaceType
         * @enum {string}
         */
        WorkplaceType: "remote" | "hybrid" | "office";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_matches_matches_get: {
        parameters: {
            query?: {
                mode?: components["schemas"]["MatchingMode"] | null;
                top?: number;
                provider?: string | null;
                model?: string | null;
                min_score?: number | null;
                /** @description Named search preset, see GET /searches */
                search?: string | null;
                /** @description Only saved / only hidden offers (default: all but hidden) */
                status?: ("saved" | "hidden") | null;
                /** @description Override search.categories */
                category?: string[] | null;
                /** @description Override search.preferred_cities */
                city?: string[] | null;
                /** @description Override search.min_salary_pln_month */
                min_salary?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_offer_offers__offer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOffer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_offer_status_offers__offer_id__status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_offer_offers__offer_id__assess_post: {
        parameters: {
            query?: {
                search?: string | null;
                provider?: string | null;
                model?: string | null;
            };
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    rebuild_profile_profile_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    upload_cv_profile_cv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cv_profile_cv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overrides_profile_overrides_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOverrides-Output"];
                };
            };
        };
    };
    put_overrides_profile_overrides_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileOverrides-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"][];
                };
            };
        };
    };
    list_categories_sources__source__categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_sync_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_sync_sync_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sync_status_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    sync_history_syncs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    searches_searches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSummaryItem"][];
                };
            };
        };
    };
    preferences_preferences_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
}
